version: "3.8"

services:
  user_registration:
    image:073449301057.dkr.ecr.us-east-1.amazonaws.com/user_registration:user
    restart: always
    build: 
      contect: .
    ports:
      - 3000:3000
    
      
  meter_ocr:
    image:073449301057.dkr.ecr.us-east-1.amazonaws.com/meter_ocr:meter
    restart: always
    build:
      contect: .
    ports:
      - 4000:4000
    


    
