version: "3.8"

services:
  src1:
    image:073449301057.dkr.ecr.us-east-1.amazonaws.com/user_registration
    container_name: user_registration

    build: .
    ports:
    - "3000:3000"
    restart: always
      
  src2:
    image:073449301057.dkr.ecr.us-east-1.amazonaws.com/meter_ocr
    container_name: meter_ocr

    build: .
    ports:
    - "4000:4000"
    restart: always


    
