version: "3.8"

services:
  user_registration:
    image:${DOCKER_REGISTRY}/user_registration:user
    restart: always
    build: 
      context: .
    ports:
      - 3000:3000
    
      
  meter_ocr:
    image:${DOCKER_REGISTRY}/meter_ocr:meter
    restart: always
    build:
      context: .
    ports:
      - 4000:4000
    


    
