version: "3"

services:
  user_registration:
    restart: always
    image: 073449301057.dkr.ecr.us-east-1.amazonaws.com/ai-spot-billing:user_registration
    build:
      #image: meter_ocr:latest
      context: .
      # cache_from:
      #   - meter_ocr:latest
    #ports:
      # - 3000:3000
    # version_tag:
    #   extends: build
    #   image: 073449301057.dkr.ecr.us-east-1.amazonaws.com/user_registration:latest
      
  meter_ocr:
    #image:${DOCKER_REGISTRY}/meter_ocr:meter
    restart: always
    image: 073449301057.dkr.ecr.us-east-1.amazonaws.com/ai-spot-billing:meter_ocr
    build:
      context: .
    # ports:
    #   - 4000:4000
    


    
