name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build and Push Docker Images
      run: |

       docker-compose build
       docker-compose tag your_service_name:latest your_ecr_repository/your_service_name:latest
      # Log in to Amazon ECR if you are using a private ECR repository
      # docker login -u AWS -p $(aws ecr get-login-password --region your_region) your_ecr_repository

    - name: Create Docker Compose File
      run: |
        # Save the Docker Compose file to a temporary location
        cp docker-compose.yml /tmp/docker-compose.yml
        # Replace "your_service_name" with the name of your service in the Docker Compose file
        sed -i 's/your_service_name/your_ecr_repository\/your_service_name/g' /tmp/docker-compose.yml

    - name: Copy Docker Compose File to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }} # EC2 instance public IP or DNS name
        username: ${{ secrets.EC2_USERNAME }} # EC2 instance username
        key: ${{ secrets.EC2_SSH_KEY }} # Private key to authenticate to EC2
       # Copy the Docker Compose file to the EC2 instance
#       args:
#       src: /tmp/docker-compose.yml
#       dest: /home/ec2-user/docker-compose.yml
    - name: E2E Test Specific - Create ssh keys
      run: |
        echo #HOME
        ls -la $HOME
        ssh-keygen -m PEM -t rsa -b 4096 -f "$HOME/.ssh/id_rsa" -N ""
        eval `ssh-agent -s`
        ssh-add "$HOME/.ssh/id_rsa"
        ssh-add -l
        echo "SSH_PRIVATE_KEY<<EOF" >> $SSH_PRIVATE_KEY
        cat $HOME/.ssh/id_rsa >> $SSH_PRIVATE_KEY
        echo "EOF" >> $SSH_PRIVATE_KEY

      

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}

    # Run Docker Compose up on the EC2 instance
      args: sudo docker-compose -f /home/ec2-user/docker-compose.yml up -d
