name: Deploy to EC2
on:
  push:
   branches:
    - main

jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v3
      
    - name: Build and Push Docker Images
      run: |
        docker-compose build
        docker-compose tag src1:latest meter-ocr/scr2:latest
        # Log in to Amazon ECR if you are using a private ECR repository
        # docker login -u AWS -p $(aws ecr get-login-password --region your_region) your_ecr_repository

    - name: Create Docker Compose File
      run: |
        # Save the Docker Compose file to a temporary location
        cp docker-compose.yml /tmp/docker-compose.yml
        # Replace "your_service_name" with the name of your service in the Docker Compose file
        sed -i 's/src1/meter-ocr\/src2/g' /tmp/docker-compose.yml

    - name: Copy Docker Compose File to EC2
      uses: appleboy/scp-action@master
      with:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # EC2 instance public IP or DNS name
        REMOTE_USER: ${{ secrets.REMOTE_USER }} # EC2 instance username
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Private key to authenticate to EC2

      # Copy the Docker Compose file to the EC2 instance
#       args:
#       src: /tmp/docker-compose.yml
#       dest: /home/ec2-user/docker-compose.yml

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@master
      with:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

#      # Run Docker Compose up on the EC2 instance
#       args: sudo docker-compose -f /home/ec2-user/docker-compose.yml up -d
